path: C:\Users\lyh70\ODPlatform\data\processed\rsod
train: train/images
val: val/images
test: test/images
nc: 4
names:
    0: aircraft
    1: oiltank
    2: overpass
    3: playground
schema_version: 1
odp_meta:
    dataset_name: rsod
    created_at: '2026-05-20 18:15:11'
    random_state: 42
    split_counts:
        train: 749
        val: 94
        test: 93
        total_input: 936
